# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\spovt\Documents\GitHub\Course_GUI_for_DB\commit_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(451, 372)
        Dialog.setStyleSheet("QWidget { background-color: rgb(13, 17, 23); } \n"
"/* QFrame { border: 2px solid rgb(0, 191, 255) } */\n"
"QTextEdit {\n"
"    background-color: rgb(13, 17, 23);\n"
"    color: rgb(255,255,255);\n"
"    font: bold 18px\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 191, 255);\n"
"    border-radius: 7px;\n"
"    background-color: rgb(13, 17, 23);\n"
"    color: rgb(255,255,255);\n"
"    font: 14px\n"
"}\n"
"QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid rgb(35, 134, 54);\n"
"    background-color: rgb(35, 134, 54);\n"
"    color: white;\n"
"    font: bold 16px\n"
"}\n"
"QPushButton#cancelButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid rgb(180, 0, 0);\n"
"    background-color: rgb(180, 0, 0);\n"
"    color: white;\n"
"    font: bold 16px\n"
"}\n"
"QCheckBox{\n"
"    color: white;\n"
"}\n"
"")
        self.summary = QtWidgets.QLineEdit(Dialog)
        self.summary.setGeometry(QtCore.QRect(10, 170, 431, 31))
        self.summary.setText("")
        self.summary.setObjectName("summary")
        self.commitButton = QtWidgets.QPushButton(Dialog)
        self.commitButton.setGeometry(QtCore.QRect(10, 330, 211, 31))
        self.commitButton.setObjectName("commitButton")
        self.passTextEdit = QtWidgets.QTextEdit(Dialog)
        self.passTextEdit.setGeometry(QtCore.QRect(10, 210, 181, 31))
        self.passTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passTextEdit.setReadOnly(True)
        self.passTextEdit.setObjectName("passTextEdit")
        self.description = QtWidgets.QLineEdit(Dialog)
        self.description.setGeometry(QtCore.QRect(10, 250, 431, 71))
        self.description.setText("")
        self.description.setObjectName("description")
        self.passTextEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.passTextEdit_3.setGeometry(QtCore.QRect(10, 130, 181, 31))
        self.passTextEdit_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passTextEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passTextEdit_3.setReadOnly(True)
        self.passTextEdit_3.setObjectName("passTextEdit_3")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(230, 330, 211, 31))
        self.cancelButton.setObjectName("cancelButton")
        self.passTextEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.passTextEdit_4.setGeometry(QtCore.QRect(10, 0, 191, 31))
        self.passTextEdit_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passTextEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passTextEdit_4.setReadOnly(True)
        self.passTextEdit_4.setObjectName("passTextEdit_4")
        self.currentRep = QtWidgets.QTextEdit(Dialog)
        self.currentRep.setGeometry(QtCore.QRect(10, 20, 191, 31))
        self.currentRep.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentRep.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentRep.setReadOnly(True)
        self.currentRep.setObjectName("currentRep")
        self.modelCheckBox = QtWidgets.QCheckBox(Dialog)
        self.modelCheckBox.setGeometry(QtCore.QRect(100, 80, 81, 21))
        self.modelCheckBox.setObjectName("modelCheckBox")
        self.passTextEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.passTextEdit_5.setGeometry(QtCore.QRect(270, 0, 171, 31))
        self.passTextEdit_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passTextEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passTextEdit_5.setReadOnly(True)
        self.passTextEdit_5.setObjectName("passTextEdit_5")
        self.currentBranch = QtWidgets.QTextEdit(Dialog)
        self.currentBranch.setGeometry(QtCore.QRect(270, 20, 171, 31))
        self.currentBranch.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentBranch.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentBranch.setReadOnly(True)
        self.currentBranch.setObjectName("currentBranch")
        self.codeCheckBox = QtWidgets.QCheckBox(Dialog)
        self.codeCheckBox.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.codeCheckBox.setObjectName("codeCheckBox")
        self.datasetCheckBox = QtWidgets.QCheckBox(Dialog)
        self.datasetCheckBox.setGeometry(QtCore.QRect(190, 80, 71, 21))
        self.datasetCheckBox.setObjectName("datasetCheckBox")
        self.LoginText = QtWidgets.QTextEdit(Dialog)
        self.LoginText.setGeometry(QtCore.QRect(270, 60, 171, 31))
        self.LoginText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LoginText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LoginText.setReadOnly(True)
        self.LoginText.setObjectName("LoginText")
        self.currentUser = QtWidgets.QTextEdit(Dialog)
        self.currentUser.setGeometry(QtCore.QRect(270, 80, 171, 31))
        self.currentUser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentUser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentUser.setReadOnly(True)
        self.currentUser.setObjectName("currentUser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.commitButton.setText(_translate("Dialog", "Commit"))
        self.passTextEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px; font-weight:400;\">Description </span><span style=\" font-size:9pt; font-weight:400; color:#6d6d6d;\">(optional)</span></p></body></html>"))
        self.passTextEdit_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px; font-weight:400;\">Summary </span><span style=\" font-size:18px; font-weight:400; color:#f14d46;\">*</span></p></body></html>"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.passTextEdit_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:400; color:#5e5e5e;\">Current repository</span></p></body></html>"))
        self.currentRep.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px; font-weight:400;\">currrep</span></p></body></html>"))
        self.modelCheckBox.setText(_translate("Dialog", "Model"))
        self.passTextEdit_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:400; color:#5e5e5e;\">Current branch</span></p></body></html>"))
        self.currentBranch.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px; font-weight:400;\">currbranch</span></p></body></html>"))
        self.codeCheckBox.setText(_translate("Dialog", "Code"))
        self.datasetCheckBox.setText(_translate("Dialog", "Dataset"))
        self.LoginText.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:400; color:#5e5e5e;\">Login</span></p></body></html>"))
        self.currentUser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px; font-weight:400;\">curruser</span></p></body></html>"))
