# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\spovt\Documents\GitHub\Course_GUI_for_DB\create_rep_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 405)
        Dialog.setStyleSheet("QWidget { background-color: rgb(13, 17, 23); } \n"
"/* QFrame { border: 2px solid rgb(0, 191, 255) } */\n"
"QTextEdit {\n"
"    background-color: rgb(13, 17, 23);\n"
"    color: rgb(255,255,255);\n"
"    font: bold 18px\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 191, 255);\n"
"    border-radius: 7px;\n"
"    background-color: rgb(13, 17, 23);\n"
"    color: rgb(255,255,255);\n"
"    font: 14px\n"
"}\n"
"QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid rgb(35, 134, 54);\n"
"    background-color: rgb(35, 134, 54);\n"
"    color: white;\n"
"    font: bold 16px\n"
"}\n"
"QPushButton#cancelButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid rgb(180, 0, 0);\n"
"    background-color: rgb(180, 0, 0);\n"
"    color: white;\n"
"    font: bold 16px\n"
"}\n"
"")
        self.newRepName = QtWidgets.QLineEdit(Dialog)
        self.newRepName.setGeometry(QtCore.QRect(220, 70, 271, 31))
        self.newRepName.setText("")
        self.newRepName.setObjectName("newRepName")
        self.createRepButton = QtWidgets.QPushButton(Dialog)
        self.createRepButton.setGeometry(QtCore.QRect(10, 360, 231, 31))
        self.createRepButton.setObjectName("createRepButton")
        self.currentUser = QtWidgets.QTextEdit(Dialog)
        self.currentUser.setGeometry(QtCore.QRect(10, 70, 171, 31))
        self.currentUser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentUser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentUser.setReadOnly(True)
        self.currentUser.setObjectName("currentUser")
        self.passTextEdit = QtWidgets.QTextEdit(Dialog)
        self.passTextEdit.setGeometry(QtCore.QRect(10, 120, 181, 31))
        self.passTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passTextEdit.setReadOnly(True)
        self.passTextEdit.setObjectName("passTextEdit")
        self.description = QtWidgets.QLineEdit(Dialog)
        self.description.setGeometry(QtCore.QRect(10, 160, 481, 61))
        self.description.setText("")
        self.description.setObjectName("description")
        self.loginTextEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.loginTextEdit_2.setGeometry(QtCore.QRect(190, 70, 21, 31))
        self.loginTextEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.loginTextEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.loginTextEdit_2.setReadOnly(True)
        self.loginTextEdit_2.setObjectName("loginTextEdit_2")
        self.passTextEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.passTextEdit_2.setGeometry(QtCore.QRect(10, 30, 81, 31))
        self.passTextEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passTextEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passTextEdit_2.setReadOnly(True)
        self.passTextEdit_2.setObjectName("passTextEdit_2")
        self.passTextEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.passTextEdit_3.setGeometry(QtCore.QRect(220, 30, 181, 31))
        self.passTextEdit_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passTextEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passTextEdit_3.setReadOnly(True)
        self.passTextEdit_3.setObjectName("passTextEdit_3")
        self.passTextEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.passTextEdit_4.setGeometry(QtCore.QRect(10, 240, 231, 31))
        self.passTextEdit_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passTextEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passTextEdit_4.setReadOnly(True)
        self.passTextEdit_4.setObjectName("passTextEdit_4")
        self.langs = QtWidgets.QLineEdit(Dialog)
        self.langs.setGeometry(QtCore.QRect(10, 280, 231, 61))
        self.langs.setText("")
        self.langs.setObjectName("langs")
        self.passTextEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.passTextEdit_5.setGeometry(QtCore.QRect(260, 240, 231, 31))
        self.passTextEdit_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passTextEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passTextEdit_5.setReadOnly(True)
        self.passTextEdit_5.setObjectName("passTextEdit_5")
        self.tags = QtWidgets.QLineEdit(Dialog)
        self.tags.setGeometry(QtCore.QRect(260, 280, 231, 61))
        self.tags.setText("")
        self.tags.setObjectName("tags")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(260, 360, 231, 31))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.createRepButton.setText(_translate("Dialog", "Create repository"))
        self.currentUser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:400;\">Login</span></p></body></html>"))
        self.passTextEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px; font-weight:400;\">Description </span><span style=\" font-size:9pt; font-weight:400; color:#6d6d6d;\">(optional)</span></p></body></html>"))
        self.loginTextEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px;\">/</span></p></body></html>"))
        self.passTextEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px; font-weight:400;\">Owner</span></p></body></html>"))
        self.passTextEdit_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px; font-weight:400;\">Repository name </span><span style=\" font-size:18px; font-weight:400; color:#f14d46;\">*</span></p></body></html>"))
        self.passTextEdit_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px; font-weight:400;\">Languages </span><span style=\" font-size:9pt; font-weight:400; color:#6d6d6d;\">(optional)</span></p></body></html>"))
        self.passTextEdit_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18px; font-weight:400;\">Tags </span><span style=\" font-size:9pt; font-weight:400; color:#6d6d6d;\">(optional)</span></p></body></html>"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
