# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\spovt\Documents\GitHub\Course_GUI_for_DB\github_ui8.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: rgb(13, 17, 23);\n"
"    color: #ffffff; \n"
"} \n"
"QFrame { border: 2px solid rgb(0, 191, 255) } \n"
"QComboBox QAbstractItemView {\n"
"  border: 2px solid rgb(128, 0, 128);\n"
"  selection-background-color: grey;\n"
"}\n"
"QComboBox {\n"
"  border: black;\n"
"  background: grey;\n"
"  color: white;\n"
"  font-size: 20px;\n"
"}\n"
"QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid rgb(35, 134, 54);\n"
"    background-color: rgb(35, 134, 54);\n"
"    color: white;\n"
"    font: bold 14px\n"
"}\n"
"QPushButton#deleteRepButton {\n"
"    border: 2px solid rgb(180, 0, 0);\n"
"    background-color: rgb(180, 0, 0);}\n"
"QPushButton#deleteBranchButton {\n"
"    border: 2px solid rgb(180, 0, 0);\n"
"    background-color: rgb(180, 0, 0);}\n"
"QPushButton#deleteCommitButton {\n"
"    border: 2px solid rgb(180, 0, 0);\n"
"    background-color: rgb(180, 0, 0);}\n"
"QTextEdit{\n"
"    color: #a5d6ff;\n"
"    font-size: 18px\n"
"}\n"

"QTextEdit#currentBranch {\n"
"    font-size: 13px\n"
"}\n"
"QTextEdit#currentCommit {\n"
"    font-size: 13px\n"
"}\n"
"QTextEdit#lastCommitowner {\n"
"    font-size: 12px\n"
"}\n"
"QTextEdit#currentBranch {\n"
"    font-size: 12px\n"
"}\n"

"QTextEdit#codeText {\n"
"    font-size: 11px\n"
"}\n"
"QTextEdit#modelText {\n"
"    font-size: 11px\n"
"}\n"
"QTextEdit#datasetText {\n"
"    font-size: 11px\n"
"}\n"

"QMessageBox {\n"
"    background-color: rgb(13, 17, 23);\n"
"    color: #ffffff; \n"
"}\n")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.repositoryList = QtWidgets.QListWidget(self.centralwidget)
        self.repositoryList.setGeometry(QtCore.QRect(10, 20, 341, 950))
        self.repositoryList.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.repositoryList.setStyleSheet("")
        self.repositoryList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.repositoryList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.repositoryList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.repositoryList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.repositoryList.setObjectName("repositoryList")
        self.branchesComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.branchesComboBox.setGeometry(QtCore.QRect(360, 20, 401, 51))
        self.branchesComboBox.setFrame(True)
        self.branchesComboBox.setObjectName("branchesComboBox")
        self.commitsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.commitsComboBox.setGeometry(QtCore.QRect(770, 20, 851, 51))
        self.commitsComboBox.setFrame(True)
        self.commitsComboBox.setObjectName("commitsComboBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(360, 320, 1541, 651))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modelText = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.modelText.setStyleSheet("")
        self.modelText.setObjectName("modelText")
        self.horizontalLayout.addWidget(self.modelText)
        self.codeText = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.codeText.setObjectName("codeText")
        self.horizontalLayout.addWidget(self.codeText)
        self.datasetText = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.datasetText.setObjectName("datasetText")
        self.horizontalLayout.addWidget(self.datasetText)
        self.summary = QtWidgets.QTextEdit(self.centralwidget)
        self.summary.setGeometry(QtCore.QRect(770, 80, 1131, 51))
        self.summary.setStyleSheet("")
        self.summary.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.summary.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.summary.setReadOnly(True)
        self.summary.setObjectName("summary")
        self.description = QtWidgets.QTextEdit(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(770, 130, 1131, 51))
        self.description.setStyleSheet("")
        self.description.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.description.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.description.setReadOnly(True)
        self.description.setObjectName("description")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1630, 20, 271, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lastCommitOwner = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.lastCommitOwner.setObjectName("lastCommitOwner")
        self.verticalLayout.addWidget(self.lastCommitOwner)
        self.lastCommitDate = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.lastCommitDate.setStyleSheet("QTextEdit { border: none }")
        self.lastCommitDate.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lastCommitDate.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lastCommitDate.setReadOnly(True)
        self.lastCommitDate.setObjectName("lastCommitDate")
        self.verticalLayout.addWidget(self.lastCommitDate)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(360, 80, 401, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.currentCommit = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.currentCommit.setStyleSheet("QTextEdit { border: none }")
        self.currentCommit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentCommit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentCommit.setReadOnly(True)
        self.currentCommit.setObjectName("currentCommit")
        self.verticalLayout_2.addWidget(self.currentCommit)
        self.currentBranch = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.currentBranch.setStyleSheet("QTextEdit { border: none }")
        self.currentBranch.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentBranch.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentBranch.setReadOnly(True)
        self.currentBranch.setObjectName("currentBranch")
        self.verticalLayout_2.addWidget(self.currentBranch)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(360, 240, 1541, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newRepButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.newRepButton.setObjectName("newRepButton")
        self.horizontalLayout_2.addWidget(self.newRepButton)
        self.newBranchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.newBranchButton.setObjectName("newBranchButton")
        self.horizontalLayout_2.addWidget(self.newBranchButton)
        self.commitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.commitButton.setObjectName("commitButton")
        self.horizontalLayout_2.addWidget(self.commitButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(360, 280, 1541, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.deleteRepButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.deleteRepButton.setObjectName("deleteRepButton")
        self.horizontalLayout_3.addWidget(self.deleteRepButton)
        self.deleteBranchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.deleteBranchButton.setObjectName("deleteBranchButton")
        self.horizontalLayout_3.addWidget(self.deleteBranchButton)
        self.deleteCommitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.deleteCommitButton.setObjectName("deleteCommitButton")
        self.horizontalLayout_3.addWidget(self.deleteCommitButton)
        self.description_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.description_2.setGeometry(QtCore.QRect(360, 180, 761, 51))
        self.description_2.setStyleSheet("")
        self.description_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.description_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.description_2.setReadOnly(True)
        self.description_2.setObjectName("description_2")
        self.description_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.description_3.setGeometry(QtCore.QRect(360, 130, 401, 51))
        self.description_3.setStyleSheet("")
        self.description_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.description_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.description_3.setReadOnly(True)
        self.description_3.setObjectName("description_3")
        self.description_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.description_4.setGeometry(QtCore.QRect(1140, 180, 761, 51))
        self.description_4.setStyleSheet("")
        self.description_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.description_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.description_4.setReadOnly(True)
        self.description_4.setObjectName("description_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1910, 26))
        self.menubar.setObjectName("menubar")
        # self.menureps = QtWidgets.QMenu(self.menubar)
        # self.menureps.setObjectName("menureps")
        self.menuprofile = QtWidgets.QMenu(self.menubar)
        self.menuprofile.setObjectName("menuprofile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # self.menubar.addAction(self.menureps.menuAction())
        self.menubar.addAction(self.menuprofile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modelText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.summary.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.description.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lastCommitOwner.setText(_translate("MainWindow", "PushButton"))
        self.lastCommitDate.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.currentCommit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.currentBranch.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newRepButton.setText(_translate("MainWindow", "Create repository"))
        self.newBranchButton.setText(_translate("MainWindow", "Create branch"))
        self.commitButton.setText(_translate("MainWindow", "Create commit"))
        self.deleteRepButton.setText(_translate("MainWindow", "Delete repository"))
        self.deleteBranchButton.setText(_translate("MainWindow", "Delete branch"))
        self.deleteCommitButton.setText(_translate("MainWindow", "Delecte commit"))
        self.description_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.description_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.description_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        # self.menureps.setTitle(_translate("MainWindow", "reps"))
        self.menuprofile.setTitle(_translate("MainWindow", "profile"))
