# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Xiaomi\Documents\GitHub\Course_GUI_for_DB\login_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(311, 303)
        Dialog.setStyleSheet("QWidget { background-color: rgb(13, 17, 23);\n color: white; } \n"
"/* QFrame { border: 2px solid rgb(0, 191, 255) } */\n"
"QTextEdit {\n"
"    background-color: rgb(13, 17, 23);\n"
"    color: rgb(255,255,255);\n"
"    font: bold 18px\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 191, 255);\n"
"    border-radius: 7px;\n"
"    background-color: rgb(13, 17, 23);\n"
"    color: rgb(255,255,255);\n"
"    font: 14px\n"
"}\n"
"QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid rgb(35, 134, 54);\n"
"    background-color: rgb(35, 134, 54);\n"
"    color: white;\n"
"    font: bold 16px\n"
"}\n"
"QPushButton#regButton {\n"
"    background-color: rgb(13, 17, 23);\n"
"    border: 2px solid rgb(13, 17, 23); ;\n"
"    color:rgb(0, 191, 255);\n"
"    font: bold 14px\n"
"}\n")

        self.loginEdit = QtWidgets.QLineEdit(Dialog)
        self.loginEdit.setGeometry(QtCore.QRect(20, 55, 271, 31))
        self.loginEdit.setText("")
        self.loginEdit.setObjectName("loginEdit")
        self.signButton = QtWidgets.QPushButton(Dialog)
        self.signButton.setGeometry(QtCore.QRect(20, 215, 271, 31))
        self.signButton.setObjectName("signButton")
        self.loginTextEdit = QtWidgets.QTextEdit(Dialog)
        self.loginTextEdit.setGeometry(QtCore.QRect(20, 15, 141, 31))
        self.loginTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.loginTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.loginTextEdit.setReadOnly(True)
        self.loginTextEdit.setObjectName("loginTextEdit")
        self.passTextEdit = QtWidgets.QTextEdit(Dialog)
        self.passTextEdit.setGeometry(QtCore.QRect(20, 105, 141, 31))
        self.passTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.passTextEdit.setReadOnly(True)
        self.passTextEdit.setObjectName("passTextEdit")
        self.passEdit = QtWidgets.QLineEdit(Dialog)
        self.passEdit.setGeometry(QtCore.QRect(20, 145, 271, 31))
        self.passEdit.setText("")
        self.passEdit.setObjectName("passEdit")
        self.exitButton = QtWidgets.QPushButton(Dialog)
        self.exitButton.setGeometry(QtCore.QRect(20, 255, 271, 31))
        self.exitButton.setStyleSheet("QPushButton {\n"
"    border-radius: 7px;\n"
"    border: 2px solid rgb(180, 0, 0);\n"
"    background-color: rgb(180, 0, 0);\n"
"    color: white;\n"
"    font: bold 16px\n"
"}")
        self.exitButton.setObjectName("exitButton")
        self.regButton = QtWidgets.QPushButton(Dialog)
        self.regButton.setGeometry(QtCore.QRect(20, 180, 71, 21))
        self.regButton.setObjectName("regButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.signButton.setText(_translate("Dialog", "Sign In"))
        self.loginTextEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:400;\">Login</span></p></body></html>"))
        self.passTextEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:400;\">Password</span></p></body></html>"))
        self.exitButton.setText(_translate("Dialog", "Exit"))
        self.regButton.setText(_translate("Dialog", "Register"))
